language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_script:
  - npm install
script:
  - npm test
  - docker build -t minsak/node .
  - docker image minsak/node

deploy:
  provider: script
  script: docker push minsak/node
  on:
    branch: master
